fix(build): add ssh key to knownhosts & identity file to configuration

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -167,18 +167,33 @@ jobs:
           echo 'Nix conf:'
           cat ~/.config/nix/nix.conf
 
+          # Pre-accept linux-builder SSH host key
+          sudo ssh-keyscan -t ed25519 -p 31022 linux-builder >> /etc/ssh/ssh_known_hosts || echo "Failed to scan linux-builder host key"
+
           # Allow Nix to connect to remote builder on port 31022
           echo 'Edit ssh_config.d:'
-          cat << EOF | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
+          sudo mkdir -p /etc/ssh/ssh_config.d
+          cat << EOF | sudo tee /etc/ssh/ssh_config.d/100-linux-builder.conf
           Host linux-builder
-            Hostname linux-builder
+            Hostname 127.0.0.1
             User builder
-            HostKeyAlias linux-builder
             Port 31022
+            IdentityFile /etc/nix/builder_ed25519
+            StrictHostKeyChecking no
+            UserKnownHostsFile /etc/ssh/ssh_known_hosts
           EOF
+
+          # Restart the ssh daemon
+          sudo systemctl restart sshd.service && echo 'Successfully restarted ssh daemon'
+
+          # Verify SSH configuration
+          echo 'Verify ssh configuration:'
+          sudo cat /etc/ssh/ssh_config.d/100-linux-builder.conf
+          sudo ssh -v -o StrictHostKeyChecking=no builder@linux-builder whoami || echo "SSH to linux-builder failed"
 
           # Restart Nix daemon
           sudo launchctl kickstart -k system/org.nixos.nix-daemon && echo 'Successfully restarted nix daemon'
+
           # Verify linux-builder is running
           echo 'org.nixos.linux-builder:'
           sudo launchctl list org.nixos.linux-builder
